name: Deploy To AKS

on:
  push:
    branches:
      - UAT

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group aks-practical-rg \
            --name ebaydevk8s \
            --overwrite-existing

      - name: Verify Cluster
        run: kubectl get nodes

      - name: Deploy Application
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Check Deployment
        run: |
          kubectl rollout status deployment/demo-app
          kubectl get pods
          kubectl get svc
